version: "3.7"

services:
  design_system_app:
    image: ds-fips:latest
    networks:
      - FIPSNET
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.http.routers.design_system.rule=Host(`design-system.fips.app.br`)
        - traefik.http.routers.design_system.entrypoints=websecure
        - traefik.http.routers.design_system.priority=1
        - traefik.http.routers.design_system.tls.certresolver=letsencryptresolver
        - traefik.http.routers.design_system.service=design_system
        - traefik.http.services.design_system.loadbalancer.server.port=80
        - traefik.http.services.design_system.loadbalancer.passHostHeader=1

networks:
  FIPSNET:
    external: true
    name: FIPSNET
